### ISSUE TITLE
Need to force chunk size for upload

### ISSUE THREAD

**Issue by mjrussell** [jdc18/ng-flow-with-java#1]
Great example for ng-flow with java, I was able to follow it quite easily. One thing I did notice that tripped me up is that because of your check [here](https://github.com/jdc18/ng-flow-with-java/blob/master/ng-flow-java/src/main/java/ec/com/mapache/ngflow/upload/FlowInfo.java#L54), you need to add an additional param to the flow js:

forceChunkSize : true

Otherwise they let the last one become larger than the size as long as its not 2*the chunk size and the file is never renamed to the finished version

**Comment by jdc18** [comment]
Thanks, I didnt know that, I ll try to update it.

**Comment by xnog** [comment]
Great, same here.

**Comment by naknomum** [comment]
thanks for reporting this!  unfortunately, i just spent the last 30 min debugging this. :)  good to know i found the right thing.  and thanks for the fix with forceChunkSize.

**Comment by jdc18** [comment]
just added forcechunksize
